import Link from "next/link";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Privacy Policy — BearCart",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-foreground/80">{children}</div>
    </section>
  );
}

function Sub({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <h3 className="text-sm font-semibold text-foreground">{title}</h3>
      {children}
    </div>
  );
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul className="list-disc space-y-1 pl-5">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-4 py-12">

          {/* Header */}
          <div className="mb-10 border-b pb-8">
            <p className="mb-1 text-xs font-semibold uppercase tracking-widest text-primary">
              Legal
            </p>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              BearCart — PalSU Campus Marketplace
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              In compliance with Republic Act No. 10173 (Data Privacy Act of 2012) · Effective Date: June 2026
            </p>
          </div>

          <div className="space-y-10">

            <Section title="1. Introduction">
              <p>
                BearCart is a campus marketplace web application developed as a student project for Palawan State University (PalSU). It allows verified PalSU students and faculty to buy and sell items through in-person transactions on campus.
              </p>
              <p>
                This Privacy Policy explains how we collect, use, store, and protect your personal data in accordance with Republic Act No. 10173, also known as the Data Privacy Act of 2012 (DPA), and its Implementing Rules and Regulations (IRR).
              </p>
              <p>
                By using BearCart, you acknowledge that you have read and understood this Privacy Policy and consent to the collection and processing of your personal data as described herein.
              </p>
            </Section>

            <Section title="2. Personal Information Controller">
              <p>
                BearCart is operated by PalSU students as an academic project under the supervision of Palawan State University. As the Personal Information Controller (PIC) under RA 10173, we are responsible for the processing of your personal data collected through this platform.
              </p>
              <p>
                As this is currently a student project, a formal Data Protection Officer (DPO) has not yet been designated. For privacy-related concerns, you may reach us through the platform's support channels.
              </p>
            </Section>

            <Section title="3. What Personal Data We Collect">
              <p>We collect only the minimum personal data necessary to operate the marketplace. This includes:</p>
              <Sub title="3.1 Data Collected Automatically from Your PSU Google Account">
                <Ul items={[
                  "Full name",
                  "PalSU institutional email address (@psu.palawan.edu.ph)",
                  "Profile picture from your Google account",
                  "University role (Student or Faculty)",
                ]} />
              </Sub>
              <Sub title="3.2 Data You Provide">
                <Ul items={[
                  "College or department",
                  "Bio or profile description (optional)",
                  "Listing information: title, description, price, category, and images of items for sale",
                  "Request posts: title, description, budget, and reference images",
                  "Messages sent through the in-app chat",
                  "Profile picture uploads (if changed from Google account default)",
                ]} />
              </Sub>
              <Sub title="3.3 Data Generated by Platform Activity">
                <Ul items={[
                  "Transaction records: items marked as sold and the associated buyer (if selected)",
                  "Saved listings",
                  "Reports submitted against listings, requests, or users",
                  "Activity timestamps",
                ]} />
              </Sub>
            </Section>

            <Section title="4. Purpose and Legal Basis for Processing">
              <p>We process your personal data for the following purposes, consistent with Section 13 of RA 10173:</p>
              <Ul items={[
                "To verify that users are legitimate PalSU students or faculty members",
                "To operate and display listings and requests on the marketplace",
                "To facilitate communication between buyers and sellers through in-app messaging",
                "To maintain transaction records for platform integrity",
                "To moderate content and enforce community standards using automated tools",
                "To allow administrators to manage the platform and respond to reports",
                "To improve the platform based on usage patterns",
              ]} />
              <p>
                The legal bases for processing your data are: (a) your consent given upon registration and use of the platform; (b) the fulfillment of our obligations to you as a user of the marketplace; and (c) the legitimate interests of the platform in ensuring a safe and functional campus marketplace.
              </p>
            </Section>

            <Section title="5. Automated Content Moderation">
              <p>
                BearCart uses OpenAI's content moderation API (Omni Moderation) to automatically screen the following types of content before they are published or delivered:
              </p>
              <Ul items={[
                "Listing titles and descriptions",
                "Images uploaded to listings",
                "Profile pictures uploaded by users",
                "Images sent through in-app chat messages",
              ]} />
              <p>
                This automated screening is done to detect and block content that is violent, sexually explicit, or otherwise inappropriate. Images and text submitted for moderation are processed by OpenAI's systems. Please refer to{" "}
                <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2 hover:text-primary/80">
                  OpenAI's Privacy Policy
                </a>{" "}
                for information on how OpenAI handles this data.
              </p>
              <p>Content flagged by the moderation system is blocked and not stored. Users are notified when their content is rejected.</p>
            </Section>

            <Section title="6. Data Sharing and Disclosure">
              <p>We do not sell, trade, or rent your personal data to third parties. Your data may be shared only in the following circumstances:</p>
              <Ul items={[
                "With other BearCart users to the extent necessary to operate the marketplace (e.g., your name and profile picture are visible to other users on listings and in chat)",
                "With OpenAI solely for the purpose of automated content moderation as described in Section 5",
                "With Supabase, our database and storage provider, which processes your data on our behalf as a data processor",
                "With PalSU administrators if required for academic or disciplinary purposes",
                "With law enforcement or government authorities if required by applicable Philippine law",
              ]} />
              <p>
                Third-party service providers (OpenAI, Supabase, Google, Vercel) are engaged as data processors and are bound by their respective data protection agreements and privacy policies.
              </p>
            </Section>

            <Section title="7. Data Storage and Retention">
              <p>
                Your personal data is stored on Supabase servers. We retain your personal data for as long as your account remains active or as necessary to fulfill the purposes described in this policy.
              </p>
              <p>
                If you request deletion of your account, we will remove your personal data from active databases within a reasonable period, subject to any legal or academic obligations to retain certain records.
              </p>
              <p>Transaction records may be retained for a longer period for platform integrity and dispute resolution purposes.</p>
            </Section>

            <Section title="8. Your Rights as a Data Subject">
              <p>Under Republic Act No. 10173 and its IRR, you have the following rights regarding your personal data:</p>
              <Ul items={[
                "Right to be informed — You have the right to know what personal data we collect, how it is used, and with whom it is shared.",
                "Right to access — You may request a copy of your personal data that we hold.",
                "Right to rectification — You may correct inaccurate or incomplete personal data through your profile settings.",
                "Right to erasure or blocking — You may request the deletion or blocking of your personal data under circumstances provided by law.",
                "Right to object — You may object to the processing of your personal data for certain purposes.",
                "Right to data portability — You may request a copy of your data in a structured, commonly used format.",
                "Right to lodge a complaint — You have the right to file a complaint with the National Privacy Commission (NPC) at www.privacy.gov.ph if you believe your data privacy rights have been violated.",
              ]} />
              <p>To exercise any of these rights, please contact us through the platform's available support channels.</p>
            </Section>

            <Section title="9. Security Measures">
              <p>
                We implement reasonable technical and organizational measures to protect your personal data against unauthorized access, disclosure, alteration, or destruction. These include:
              </p>
              <Ul items={[
                "Authentication through PalSU Google accounts",
                "Row-level security policies on our database",
                "Automated content moderation to prevent harmful content",
                "HTTPS encryption for all data in transit",
              ]} />
              <p>
                However, no system is completely secure. While we strive to protect your data, we cannot guarantee absolute security. You are responsible for maintaining the confidentiality of your account credentials.
              </p>
            </Section>

            <Section title="10. Cookies and Session Data">
              <p>
                BearCart uses cookies and session tokens solely to maintain your login session. We do not use cookies for advertising or tracking purposes. By using the platform, you consent to the use of session cookies as described here.
              </p>
            </Section>

            <Section title="11. Changes to This Privacy Policy">
              <p>
                We may update this Privacy Policy from time to time. Changes will be posted on the platform and the effective date will be updated accordingly. Continued use of BearCart after any changes constitutes your acceptance of the updated policy.
              </p>
            </Section>

            <Section title="12. Contact and Complaints">
              <p>
                For questions, concerns, or requests related to this Privacy Policy or the processing of your personal data, please reach out through BearCart's available support channels within the platform.
              </p>
              <p>You also have the right to file a complaint directly with the National Privacy Commission of the Philippines:</p>
              <div className="rounded-lg border bg-muted/40 p-4 text-sm">
                <p className="font-semibold text-foreground">National Privacy Commission</p>
                <p>5th Floor Delegation Building, PICC Complex, Pasay City, Metro Manila</p>
                <p>
                  Website:{" "}
                  <a href="https://www.privacy.gov.ph" target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2 hover:text-primary/80">
                    www.privacy.gov.ph
                  </a>
                </p>
                <p>
                  Email:{" "}
                  <a href="mailto:info@privacy.gov.ph" className="text-primary underline underline-offset-2 hover:text-primary/80">
                    info@privacy.gov.ph
                  </a>
                </p>
              </div>
            </Section>

          </div>

          {/* Footer note */}
          <div className="mt-12 border-t pt-6 text-xs text-muted-foreground">
            <p>BearCart — PalSU Campus Marketplace · Effective Date: June 2026</p>
            <p>This document is prepared in compliance with Republic Act No. 10173 (Data Privacy Act of 2012) of the Philippines.</p>
            <div className="mt-4">
              <Link href="/terms-of-service" className="text-primary hover:underline">
                View Terms of Service →
              </Link>
            </div>
          </div>

        </div>
      </main>
      <Footer />
    </div>
  );
}
